# 链接样式，参考 http://jekyllrb.com/docs/permalinks
permalink: /:categories/:year-:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
paginate: 5

markdown: redcarpet             # markdown 语法解释引擎 #  markdown: kramdown
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
# 参考 http://github.com/vmg/redcarpet/blob/master/README.markdown

# 核心设置
title : macrobellevue
tagline:  We are drowning in information and starving for knowledge
keywords : Computational Biology, Python, R, Lisp, C++, C & Algorithm
description:  A blog focus on algorithm of structure and genomics
author :
  name : XIN ZHOU
  email : xinchoubiology@gmail.com
  github : xinchoubiology
  gitcafe : 
  twitter :
  facebook :
  feedburner :
  weibo : xcSuns

# 域名连接
#production_url : 

# Jekyll Bootstrap
JB :
  version : 0.3.0

  BASE_PATH : false                 # 如果不懂参数，请不要更改
  ASSET_PATH : false                # 同上

  # page
  about_path: /about.html
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # 评论，provider 留空或 false 关闭评论
  comments :
    provider :  disqus                     # 采用那种评论，可填 duoshuo 或 disqus 或其他 ...
    disqus :
      short_name : Xinchoubiology

  # 网站统计
  analytics :
    provider :                      # 采用那种统计，可填 baidu 或 google 或其他 ...
    google :
        tracking_id : 
    getclicky :
        site_id :
    mixpanel :
        token : 
    piwik :
        baseURL :  # Piwik installation address (without protocol)
        idsite :            # the id of the site on Piwik
    baidu :
        siteid:        # 百度统计 js 代码后的字符串

  # 一键分享
  sharing :
    provider :                      # 参考 _includes/JB/sharing

  # CDN 加速资源
  cdn :
    jquery :
      js : //cdn.bootcss.com/jquery/2.1.0/jquery.min.js
    webfont : true                  # google-fonts 开关，false 为关，留空或 true 为打开
    google-fonts :
      js : //cdn.bootcss.com/webfont/1.3.0/webfont.min.js
    font-awesome :
      css : //cdn.bootcss.com/font-awesome/4.0.3/css/font-awesome.min.css
    bootstrap :
      js : //cdn.bootcss.com/twitter-bootstrap/3.1.1/js/bootstrap.min.js
      css : //cdn.bootcss.com/twitter-bootstrap/3.1.1/css/bootstrap.min.css
    fancybox :
      js : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
      css : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css

  # 友情链接
  blogroll : false                   # true 开启，留空或 false 关闭
  brlist :
    - text : My original site
      url : //xinchoubiology.github.io/macroEnsemble
